### PR TITLE
upgrade pkg nats-server to 2.7.2

### PR DESCRIPTION
**Pull request by marcolan018**
Signed-off-by: marcolan018 <llan@redhat.com>
https://github.com/stolostron/backlog/issues/20203

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by dislbenn** [comment]
@marcolan018 @pshickeydev I added a hold since I believe the `2.5` code freeze has started. Are we able to merge this fix? If so, we just need to `unhold` the PR.

**Comment by pshickeydev** [comment]
@nelsonjean requesting approval to merge. Recommended if there will be an RC2 that we merge prior, but defer to 2.5.1 if RC1 is used.

**Pull request merged**
